### ISSUE TITLE
Missing dependencys

### ISSUE THREAD

**Issue by hwielenberg** [CRogers/LLVM-Windows-Binaries#2]
Hi,

nice work!
but I can't use the dll file because some dependent dll's are missing.
Did you compiled it with windows 8, because i guess those dll are only part of win8 and not 7.

**Comment by hwielenberg** [comment]
Hi,

just saw on the other bug Ticket that win8 was used.

Maybe i'll recompile it with win7 and push a win7 version here too.

**Comment by hastebrot** [comment]
Hi hewie!

> Maybe i'll recompile it with win7 and push a win7 version here too.

That would be nice. I first thought installing the Redistributable under Windows 7 will be fine. But it still complained about missing DLLs.

**Comment by semiessessi** [comment]
Really? What DLL does it complain about?

It depends on the VS 2013 redistributable package...

**Comment by hastebrot** [comment]
The missing DLL is `MSVCP120.dll`. System is Windows 7 64-bit. I used the redistributable from http://www.microsoft.com/en-gb/download/details.aspx?id=40784.

**Comment by semiessessi** [comment]
ok. i'll see if i can test on a clean win7 machine and work out the fix... from what i understand that is 'just' the dynamically linked bits of the C++ standard library and should be installed by the redist package at that link.

but obviously something is not working as i expect...

**Comment by semiessessi** [comment]
i've now tested on windows 7, but 32-bit. it complained about MSVC_R_120.dll instead of MSVCP - the error message was 'fixed' by installing the x86 redistributable package at the link you mention. hopefully i can find a 64-bit version somewhere to try repro with.

you might need the x86 version of the runtime rather than x64 - i'm not entirely sure, but the build done was against the default 32-bit 'Win32' platform in the solution settings...

**Comment by hastebrot** [comment]
Hey, it worked with `vcredist_x86.exe`. Thanks!

**Comment by semiessessi** [comment]
Cool. I'll update the instructions when I can - and look into removing the dependency or providing an installer or something.... :)
